add PUID PGID Variables, /data path
thetarkus/docker-templates pull request #1
Opened 2019-01-15 21:29 UTC by LuxAetern

adds the PUID and PGID Variables to the template (Unraid mostly uses 99 and 100 (nobody users))

Sets the default path for /data to /mnt/appdata/funkwhale
(standard for unraid)

Move these settings into the hidden "Advanced" part of the Template

2019-01-15 22:36 UTC, michaelmob requested changes
Thanks! This mostly looks good. There are a couple of things that, I think, should be changed.

2019-01-15 22:36 UTC, thetarkus commented on funkwhale.xml
> +        <Variable>
These variables should be in the `<Environment>` tag on line 31

2019-01-15 22:36 UTC, thetarkus commented on funkwhale.xml
> +  <Config Name="Data Path" Target="/data" Default="/mnt/user/appdata/funkwhale" Mode="rw" Description="Container Path: /config" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/u
I think there's a typo here: `/config` should be `/data` in the description

2019-01-16 13:57 UTC, LuxAetern commented
fixed both
i have no idea where that /config came from...

2019-01-16 16:00 UTC, merged

2019-01-16 16:01 UTC, thetarkus commented
Perfect! Thank you.